//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int id { get; set; }
        public string titulo_noticia { get; set; }
        public System.DateTime fecha_noticia { get; set; }
        public int autor { get; set; }
        public string descripcion_noticia { get; set; }
    
        public virtual Autor Autor1 { get; set; }
    }
}
